# Generated by Django 6.0.2 on 2026-05-04 15:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artefact",
            fields=[
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("file", models.FileField(upload_to="artefacts/")),
                (
                    "original_name",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                ("type", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="RunExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "engine_run_id",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("worker_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("seed", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "Pending"),
                            ("PREPARING", "Preparing"),
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        editable=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("version", models.IntegerField()),
                (
                    "artefact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experiments",
                        to="core.artefact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RPCLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine_run_id", models.UUIDField()),
                ("event_time", models.DateTimeField()),
                ("rpc_name", models.CharField(max_length=64)),
                ("rpc_call_id", models.UUIDField()),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("REQUEST", "Request"),
                            ("RESPONSE", "Response"),
                            ("INFO", "Info"),
                        ]
                    ),
                ),
                ("payload", models.JSONField()),
                (
                    "run_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rpc_logs",
                        to="core.runexecution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("worker_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("simulation_parameters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "Pending"),
                            ("PREPARING", "Preparing"),
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        editable=False,
                    ),
                ),
                ("rerun_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "run_signature",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run_requests",
                        to="core.experiment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="runexecution",
            name="run_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="core.runrequest",
            ),
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artefacts",
                    models.ManyToManyField(
                        related_name="scenarios", to="core.artefact"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="runrequest",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="run_requests",
                to="core.scenario",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine_run_id", models.UUIDField()),
                ("event_time", models.DateTimeField()),
                ("simulation_time", models.FloatField()),
                ("simulation_step", models.IntegerField()),
                ("subscription_fingerprint", models.CharField(max_length=256)),
                ("payload", models.JSONField()),
                (
                    "run_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_logs",
                        to="core.runexecution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TelemetryLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine_run_id", models.UUIDField()),
                ("event_time", models.DateTimeField()),
                ("simulation_time", models.FloatField()),
                ("simulation_step", models.IntegerField()),
                ("telemetry_name", models.CharField(max_length=256)),
                ("payload", models.JSONField()),
                (
                    "run_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_logs",
                        to="core.runexecution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransformationInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_name", models.CharField(max_length=255)),
                (
                    "artefact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derivatives",
                        to="core.artefact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransformationOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=64)),
                (
                    "artefact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provenance",
                        to="core.artefact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransformationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("worker_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("method", models.CharField(max_length=64)),
                ("spec_snapshot", models.JSONField()),
                ("parameters", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "Pending"),
                            ("PREPARING", "Preparing"),
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        editable=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "input_artefacts",
                    models.ManyToManyField(
                        related_name="transformation_requests",
                        through="core.TransformationInput",
                        to="core.artefact",
                    ),
                ),
                (
                    "output_artefacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="produced_by",
                        through="core.TransformationOutput",
                        to="core.artefact",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transformationoutput",
            name="transformation_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="output_bindings",
                to="core.transformationrequest",
            ),
        ),
        migrations.AddField(
            model_name="transformationinput",
            name="transformation_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="input_bindings",
                to="core.transformationrequest",
            ),
        ),
        migrations.CreateModel(
            name="WorkerLogEntryRunExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("exception_type", models.CharField(blank=True, max_length=255)),
                ("traceback", models.TextField(blank=True)),
                (
                    "run_execution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_logs",
                        to="core.runexecution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerLogEntryRunRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("exception_type", models.CharField(blank=True, max_length=255)),
                ("traceback", models.TextField(blank=True)),
                (
                    "run_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_logs",
                        to="core.runrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerLogEntryTransformRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("exception_type", models.CharField(blank=True, max_length=255)),
                ("traceback", models.TextField(blank=True)),
                (
                    "transform_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_logs",
                        to="core.transformationrequest",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="experiment",
            constraint=models.UniqueConstraint(
                fields=("name", "version"), name="unique_name_version"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transformationinput",
            unique_together={("transformation_request", "input_name")},
        ),
        migrations.AddIndex(
            model_name="workerlogentryrunexecution",
            index=models.Index(
                fields=["run_execution", "created_at"],
                name="core_worker_run_exe_c044bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workerlogentryrunrequest",
            index=models.Index(
                fields=["run_request", "created_at"],
                name="core_worker_run_req_97698a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workerlogentrytransformrequest",
            index=models.Index(
                fields=["transform_request", "created_at"],
                name="core_worker_transfo_adfc4e_idx",
            ),
        ),
    ]
