# Generated by Django 6.0.2 on 2026-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_experiment_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentgraph",
            name="version",
            field=models.IntegerField(default=0),
        ),
    ]
