# Generated by Django 6.0.2 on 2026-05-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_experiment_total_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="runexecution",
            name="current_step",
            field=models.IntegerField(default=0),
        ),
    ]
