# Generated by Django 6.0.2 on 2026-06-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_runexecution_current_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="runrequest",
            name="open_gui",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="subscriptionlogentry",
            index=models.Index(
                fields=["run_execution", "subscription_fingerprint"],
                name="core_subscr_run_exe_5fd740_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionlogentry",
            index=models.Index(
                fields=["run_execution", "subscription_fingerprint", "simulation_time"],
                name="core_subscr_run_exe_fbeaad_idx",
            ),
        ),
    ]
