# Generated by Django 6.0.2 on 2026-06-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_runrequest_open_gui_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="runrequest",
            name="step_length_ms",
            field=models.IntegerField(default=1000),
        ),
    ]
