"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from trafficgym.api import engine_pb2 as _engine_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class EngineServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> EngineServiceAsyncStub: ...
    CreateRun: _grpc.UnaryUnaryMultiCallable[_engine_pb2.CreateRunRequest, _engine_pb2.CreateRunResponse]
    Run: _grpc.UnaryUnaryMultiCallable[_engine_pb2.RunRequest, _engine_pb2.RunResponse]
    CloseRun: _grpc.UnaryUnaryMultiCallable[_engine_pb2.CloseRunRequest, _engine_pb2.CloseRunResponse]
    ApplyActions: _grpc.UnaryUnaryMultiCallable[_engine_pb2.ActionBundle, _engine_pb2.ApplyActionsResponse]
    StreamTelemetry: _grpc.UnaryStreamMultiCallable[_engine_pb2.StreamRequest, _engine_pb2.TelemetryFrame]
    StreamSubscriptions: _grpc.UnaryStreamMultiCallable[_engine_pb2.StreamRequest, _engine_pb2.TelemetryFrame]
    Subscribe: _grpc.UnaryUnaryMultiCallable[_engine_pb2.SubscribeRequest, _engine_pb2.SubscribeResponse]
    Unsubscribe: _grpc.UnaryUnaryMultiCallable[_engine_pb2.UnsubscribeRequest, _engine_pb2.UnsubscribeResponse]
    RegisterInterrupt: _grpc.UnaryStreamMultiCallable[_engine_pb2.RegisterInterruptRequest, _engine_pb2.InterruptEvent]
    AcknowledgeInterrupt: _grpc.UnaryUnaryMultiCallable[_engine_pb2.AcknowledgeInterruptRequest, _engine_pb2.ApplyActionsResponse]
    CancelInterrupt: _grpc.UnaryUnaryMultiCallable[_engine_pb2.CancelInterruptRequest, _engine_pb2.CancelInterruptResponse]
    FetchSubscription: _grpc.UnaryUnaryMultiCallable[_engine_pb2.FetchRequest, _engine_pb2.FetchResponse]

@_typing.type_check_only
class EngineServiceAsyncStub(EngineServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    CreateRun: _aio.UnaryUnaryMultiCallable[_engine_pb2.CreateRunRequest, _engine_pb2.CreateRunResponse]  # type: ignore[assignment]
    Run: _aio.UnaryUnaryMultiCallable[_engine_pb2.RunRequest, _engine_pb2.RunResponse]  # type: ignore[assignment]
    CloseRun: _aio.UnaryUnaryMultiCallable[_engine_pb2.CloseRunRequest, _engine_pb2.CloseRunResponse]  # type: ignore[assignment]
    ApplyActions: _aio.UnaryUnaryMultiCallable[_engine_pb2.ActionBundle, _engine_pb2.ApplyActionsResponse]  # type: ignore[assignment]
    StreamTelemetry: _aio.UnaryStreamMultiCallable[_engine_pb2.StreamRequest, _engine_pb2.TelemetryFrame]  # type: ignore[assignment]
    StreamSubscriptions: _aio.UnaryStreamMultiCallable[_engine_pb2.StreamRequest, _engine_pb2.TelemetryFrame]  # type: ignore[assignment]
    Subscribe: _aio.UnaryUnaryMultiCallable[_engine_pb2.SubscribeRequest, _engine_pb2.SubscribeResponse]  # type: ignore[assignment]
    Unsubscribe: _aio.UnaryUnaryMultiCallable[_engine_pb2.UnsubscribeRequest, _engine_pb2.UnsubscribeResponse]  # type: ignore[assignment]
    RegisterInterrupt: _aio.UnaryStreamMultiCallable[_engine_pb2.RegisterInterruptRequest, _engine_pb2.InterruptEvent]  # type: ignore[assignment]
    AcknowledgeInterrupt: _aio.UnaryUnaryMultiCallable[_engine_pb2.AcknowledgeInterruptRequest, _engine_pb2.ApplyActionsResponse]  # type: ignore[assignment]
    CancelInterrupt: _aio.UnaryUnaryMultiCallable[_engine_pb2.CancelInterruptRequest, _engine_pb2.CancelInterruptResponse]  # type: ignore[assignment]
    FetchSubscription: _aio.UnaryUnaryMultiCallable[_engine_pb2.FetchRequest, _engine_pb2.FetchResponse]  # type: ignore[assignment]

class EngineServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def CreateRun(
        self,
        request: _engine_pb2.CreateRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.CreateRunResponse, _abc.Awaitable[_engine_pb2.CreateRunResponse]]: ...

    @_abc_1.abstractmethod
    def Run(
        self,
        request: _engine_pb2.RunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.RunResponse, _abc.Awaitable[_engine_pb2.RunResponse]]: ...

    @_abc_1.abstractmethod
    def CloseRun(
        self,
        request: _engine_pb2.CloseRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.CloseRunResponse, _abc.Awaitable[_engine_pb2.CloseRunResponse]]: ...

    @_abc_1.abstractmethod
    def ApplyActions(
        self,
        request: _engine_pb2.ActionBundle,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.ApplyActionsResponse, _abc.Awaitable[_engine_pb2.ApplyActionsResponse]]: ...

    @_abc_1.abstractmethod
    def StreamTelemetry(
        self,
        request: _engine_pb2.StreamRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_engine_pb2.TelemetryFrame], _abc.AsyncIterator[_engine_pb2.TelemetryFrame]]: ...

    @_abc_1.abstractmethod
    def StreamSubscriptions(
        self,
        request: _engine_pb2.StreamRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_engine_pb2.TelemetryFrame], _abc.AsyncIterator[_engine_pb2.TelemetryFrame]]: ...

    @_abc_1.abstractmethod
    def Subscribe(
        self,
        request: _engine_pb2.SubscribeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.SubscribeResponse, _abc.Awaitable[_engine_pb2.SubscribeResponse]]: ...

    @_abc_1.abstractmethod
    def Unsubscribe(
        self,
        request: _engine_pb2.UnsubscribeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.UnsubscribeResponse, _abc.Awaitable[_engine_pb2.UnsubscribeResponse]]: ...

    @_abc_1.abstractmethod
    def RegisterInterrupt(
        self,
        request: _engine_pb2.RegisterInterruptRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_engine_pb2.InterruptEvent], _abc.AsyncIterator[_engine_pb2.InterruptEvent]]: ...

    @_abc_1.abstractmethod
    def AcknowledgeInterrupt(
        self,
        request: _engine_pb2.AcknowledgeInterruptRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.ApplyActionsResponse, _abc.Awaitable[_engine_pb2.ApplyActionsResponse]]: ...

    @_abc_1.abstractmethod
    def CancelInterrupt(
        self,
        request: _engine_pb2.CancelInterruptRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.CancelInterruptResponse, _abc.Awaitable[_engine_pb2.CancelInterruptResponse]]: ...

    @_abc_1.abstractmethod
    def FetchSubscription(
        self,
        request: _engine_pb2.FetchRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.FetchResponse, _abc.Awaitable[_engine_pb2.FetchResponse]]: ...

def add_EngineServiceServicer_to_server(servicer: EngineServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
