/// TrafficGym Engine API
///
/// Manages SUMO Simulation runs via libusmo.
/// Provides public API to implemnent an experimentation engine on top of SUMO.


syntax = "proto3";

import "google/protobuf/struct.proto";

package sumo.engine.v1;

message NamedNullableString {
    string name = 1;
    bool has_value = 2;
    string value = 3;
}

message CustomValue {
  oneof kind {
    google.protobuf.NullValue null_value = 1;
    int64 int_value = 2;
    double float_value = 3;
    string string_value = 4;
    bool bool_value = 5;
    google.protobuf.Struct struct_value = 6;
    google.protobuf.ListValue list_value = 7;
  }
}

message TelemetryFrame {
  string run_id = 1;
  int64 step = 2;
  double sim_time_s = 3;
  repeated NamedNullableString metrics = 4;
}

message GenericSetter {
  string domain = 1;
  string setter_name = 2;
  string object_id = 3;
  repeated Parameter parameters = 4;
}

message Action {
  oneof payload {
    GenericSetter setter = 2;
  }
}

message ApplyActionsRequest {
  string run_id = 1;
  ActionBundle action_bundle = 2;
}

message ActionBundle {
  optional int64 step = 2;
  repeated Action actions = 3;
}

// message Artifact {
//   string artifact_id = 1;
//   string type = 2;
//   string uri = 3;
//   string sha256 = 4;
// }

message CreateRunRequest {
  string sumocfg_path = 1;
  string sumo_binary = 2;
  int32 step_length_ms = 3;
  int32 seed = 4;
}

message CreateRunResponse {
  string run_id = 1;
  // repeated Artifact input_artifacts = 2;
}

message RunRequest {
  string run_id = 1;

  oneof run_mode {
    int32 max_steps = 2;
    float max_time = 3;
    int32 steps = 4;
    float time = 5;
  }
}

message RunResponse {
  string run_id = 1;
  uint64 new_step = 2;
  float new_time = 3;
}

message CloseRunRequest {
  string run_id = 1;
}

message CloseRunResponse {
  string run_id = 1;
  // maybe can return some analytics also?
}

message ApplyActionsResponse {
  repeated string errors = 1;
}

message StreamRequest {
  string run_id = 1;
}

message Parameter {
  string name = 1;
  CustomValue value = 2;
}

message SubscribeRequest {
  string run_id = 1;
  string domain = 2;
  string getter_name = 3;
  string object_id = 4;
  repeated Parameter parameters = 5;
  optional string name = 6;
}

message SubscribeResponse {
  string fingerprint = 1;
}

message UnsubscribeRequest {
  string run_id = 1;
}

message UnsubscribeResponse {
  string run_id = 1;
}

enum Operation {
  EQU = 0;
  NEQ = 1;
  GRT = 2;
  LST = 3;
  GEQ = 4;
  LEQ = 5;
}

message TriggerMetricNameAndValue {
  // TODO coalesce with Parameter, which shares name and value
  string subscription_fingerprint = 1;
  CustomValue value = 2;
  Operation op = 3;
}

message RegisterInterruptRequest {
  string run_id = 1;
  TriggerMetricNameAndValue trigger_metric = 2;
}

message RegisterInterruptResponse {
  string interrupt_id = 1;
}

message StreamInterruptsRequest {
  string run_id = 1;
  string interrupt_id = 2;
}

message InterruptEvent {
  string run_id = 1;
  string interrupt_id = 2;
  string event_id = 3;
  // maybe following fields optional?
  string observed_value = 4;
}

message AcknowledgeInterruptRequest {
  string run_id = 1;
  string interrupt_id = 2;
  string event_id = 3;
  ActionBundle actions = 4;
  TriggerMetricNameAndValue new_interrupt_conditions = 5;
}

message CancelInterruptRequest {
  string run_id = 1;
  string interrupt_id = 2;
}

message CancelInterruptResponse {
  string interrupt_id = 1;
}

message FetchRequest {
  string run_id = 1;
  string fingerprint = 2;
  bool requires_collect = 3;
}

message FetchResponse {
  NamedNullableString fetched = 1;
}

// ------------ DERIVE FROM ARTEFACT ---------------

message DeriveFromArtefactRequest {
  string base_path = 1;
  string method = 2;
  map<string, string> parameters = 3;
  map<string, string> target_file_paths = 4;
}

message DeriveFromArtefactResponse {
  repeated string errors = 1;
  repeated string warnings = 2;
  map<string, string> derived_artefact_paths = 3;
}

enum InputType {
  INPUT_TYPE_UNSPECIFIED = 0;
  FILE = 1;
  JSON = 2;
}

message InputSpec {
  string name = 1;
  InputType type = 2;
  bool required = 3;
}

message TransformationSpec {
  string key = 1;
  repeated InputSpec inputs = 2;
  repeated string outputs = 3;
  string docstring = 4;
}

message ListTransformationsRequest {}

message ListTransformationsResponse {
  repeated TransformationSpec transformations = 1;
}

// EngineSerivce manages a SUMO simulation lifecycle and provides runtime control
//
// Users can create runs, create subscriptions which will collect data from the simulation
// and make it accessible via SubscriptionStream or FetchSubscription
// 
// Users step the simulation via Run and can change any simulation parameter accessible via
// the TraCI API using ApplyActions. They can also set interrupts via RegisterInterrupt, which
// will interrupt Run requests, by issuing an InterruptEvent. Users must then acknowledge the
// interrupt via AcknowledgeInterrupt and can provide ApplyAction parameters to change the simulation
// before any previously request Run continues. They can also provide new conditions for which the interrupt
// should trigger; by default they are cancelled on acknowledgement.
service EngineService {

  // CreateRun initialises the simulation engine in such a way that it can subsequently be stepped.
  //
  // Input:
  //
  // - `sumocfg_path` str: A path to a SUMO config file
  // - `sumo_binary` str: One of "sumo-gui" or "sumo". Running with "sumo-gui" is experiemental due to a `libsumo` limitation.
  // - `step_length_ms` int > 0: Optional integer value which sets how many milliseconds each simulation step should step.
  //
  // Preconditions:
  //
  // - `SUMO_HOME` must be declared with the correct path to a SUMO executable
  //
  // Postconditions:
  //
  // - A run_id is returned to the user. All preparations have been made, so any other coroutine can now be used.
  //
  // Output:
  //
  // - `run_id`: A string containing a UUID for the run that was just created.
  //
  // Failure Modes:
  //
  // - `INVALID_ARGUMENT`: The run could not be started, such as when the `sumocfg_path` is invalid
  rpc CreateRun(CreateRunRequest) returns (CreateRunResponse);

  // Run steps the simulation forward
  //
  // Invoking run causes the simulation to step forward by `steps`, `time`, or until `max-steps` or `max-time` are reached.
  // For now, only `steps` is supported. Run can be interrupted by registering interrupts via RegisterInterrupt.
  //
  // Input:
  //
  // - `run_id` str: A valid `run_id`, obtained in the response of CreateRun
  // - `run_mode`: ONE OF `steps`, `time`, `max_steps`, or `max_time`. Not `max_steps` and `max_time` are currently unsupported.
  //
  // Preconditions:
  //
  // - The run was created (implicit because there is no other way to obtain `run_id`) 
  // - Only one run can be executing at a time (no concurrent runs).
  //
  // Postconditions:
  //
  // - The run is stepped as forward as requested. If multiple `run_modes` were specified, the last written field from gRPC's perspective will be used.
  // - If interrupt trigger conditions were met, their actions were applied before the next step occurred.
  //
  // Output:
  //
  // - `run_id`: The run that was just stepped
  // - `new_step`: The step number that was last applied; the next step will be `new_step` + 1.
  // - `new_time`: The timestamp (in seconds) of the simulation after this Run finished.
  //
  // Failure Modes:
  //
  // - `NOT_FOUND`: The `run_id` was not found in the list of created runs.
  // - `ALREADY_EXISTS`: A run is currently executing for this `run_id`.
  // - `ABORTED`: The run with id `run_id` was closed and can no longer be stepped.
  // - `UNIMPLEMENTED`: The request asked to step via `max_step` or `max_time`, these are currently unsupported.
  // - `INVALID_ARGUMENT`: The request did not specify the run_mode.
  rpc Run(RunRequest) returns (RunResponse);

  // CloseRun closes a run
  //
  // Invoking CloseRun causes the specified run to transition to a state where it is no longer possible to call Run or ApplyActions for that run. The connection via `libsumo` is also severed.
  //
  // Inputs:
  //
  // - `run_id` str: A valid `run_id`, obtained in the response of CreateRun
  //
  // Preconditions:
  // 
  // - A run is not currently executing for `run_id`. A warning will be issued, but the run will be left in an undefined state.
  // - The run is not already closed
  //
  // Postconditions:
  //
  // - All existing subscriptions for this run are cancelled
  // - run_id remains preserved to query historical run data.
  // - The run will no longer be modifiable via other coroutines.
  //
  // Outputs:
  //
  // - `run_id` str: The run_id of the run that was just closed.
  //
  // Failure Modes:
  //
  // - `NOT_FOUND`: The `run_id` was not found in the list of created runs.
  // - `INVALID_ARGUMENT`: The specified run was already closed.
  rpc CloseRun(CloseRunRequest) returns (CloseRunResponse);

  // ApplyActions
  rpc ApplyActions(ApplyActionsRequest) returns (ApplyActionsResponse);

  // StreamTelemetry
  rpc StreamTelemetry(StreamRequest) returns (stream TelemetryFrame);

  // StreamSubscriptions
  rpc StreamSubscriptions(StreamRequest) returns (stream TelemetryFrame);

  // Subscribe
  rpc Subscribe(SubscribeRequest) returns (SubscribeResponse);

  // Unsubscribe
  rpc Unsubscribe(UnsubscribeRequest) returns (UnsubscribeResponse);

  // RegisterInterrupt
  rpc RegisterInterrupt(RegisterInterruptRequest) returns (RegisterInterruptResponse);

  rpc StreamInterrupts(StreamInterruptsRequest) returns (stream InterruptEvent);

  // AcknowledgeInterrupt
  rpc AcknowledgeInterrupt(AcknowledgeInterruptRequest) returns (ApplyActionsResponse);

  // CancelInterrupt
  rpc CancelInterrupt(CancelInterruptRequest) returns (CancelInterruptResponse);

  // FetchSubscription
  rpc FetchSubscription(FetchRequest) returns (FetchResponse);

  // ------------ DERIVE FROM ARTEFACT ---------------

  rpc DeriveFromArtefact(DeriveFromArtefactRequest) returns (DeriveFromArtefactResponse);

  rpc ListTransformations(ListTransformationsRequest) returns (ListTransformationsResponse);
}

