"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
/ TrafficGym Engine API
/
/ Manages SUMO Simulation runs via libusmo.
/ Provides public API to implemnent an experimentation engine on top of SUMO.
"""

from collections import abc as _abc
from grpc import aio as _aio
from trafficgym.api import engine_pb2 as _engine_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class EngineServiceStub:
    """EngineSerivce manages a SUMO simulation lifecycle and provides runtime control

    Users can create runs, create subscriptions which will collect data from the simulation
    and make it accessible via SubscriptionStream or FetchSubscription

    Users step the simulation via Run and can change any simulation parameter accessible via
    the TraCI API using ApplyActions. They can also set interrupts via RegisterInterrupt, which
    will interrupt Run requests, by issuing an InterruptEvent. Users must then acknowledge the
    interrupt via AcknowledgeInterrupt and can provide ApplyAction parameters to change the simulation
    before any previously request Run continues. They can also provide new conditions for which the interrupt
    should trigger; by default they are cancelled on acknowledgement.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> EngineServiceAsyncStub: ...
    CreateRun: _grpc.UnaryUnaryMultiCallable[_engine_pb2.CreateRunRequest, _engine_pb2.CreateRunResponse]
    """CreateRun initialises the simulation engine in such a way that it can subsequently be stepped.

    Input:

    - `sumocfg_path` str: A path to a SUMO config file
    - `sumo_binary` str: One of "sumo-gui" or "sumo". Running with "sumo-gui" is experiemental due to a `libsumo` limitation.
    - `step_length_ms` int > 0: Optional integer value which sets how many milliseconds each simulation step should step.

    Preconditions:

    - `SUMO_HOME` must be declared with the correct path to a SUMO executable

    Postconditions:

    - A run_id is returned to the user. All preparations have been made, so any other coroutine can now be used.

    Output:

    - `run_id`: A string containing a UUID for the run that was just created.

    Failure Modes:

    - `INVALID_ARGUMENT`: The run could not be started, such as when the `sumocfg_path` is invalid
    """
    Run: _grpc.UnaryUnaryMultiCallable[_engine_pb2.RunRequest, _engine_pb2.RunResponse]
    """Run steps the simulation forward

    Invoking run causes the simulation to step forward by `steps`, `time`, or until `max-steps` or `max-time` are reached.
    For now, only `steps` is supported. Run can be interrupted by registering interrupts via RegisterInterrupt.

    Input:

    - `run_id` str: A valid `run_id`, obtained in the response of CreateRun
    - `run_mode`: ONE OF `steps`, `time`, `max_steps`, or `max_time`. Not `max_steps` and `max_time` are currently unsupported.

    Preconditions:

    - The run was created (implicit because there is no other way to obtain `run_id`) 
    - Only one run can be executing at a time (no concurrent runs).

    Postconditions:

    - The run is stepped as forward as requested. If multiple `run_modes` were specified, the last written field from gRPC's perspective will be used.
    - If interrupt trigger conditions were met, their actions were applied before the next step occurred.

    Output:

    - `run_id`: The run that was just stepped
    - `new_step`: The step number that was last applied; the next step will be `new_step` + 1.
    - `new_time`: The timestamp (in seconds) of the simulation after this Run finished.

    Failure Modes:

    - `NOT_FOUND`: The `run_id` was not found in the list of created runs.
    - `ALREADY_EXISTS`: A run is currently executing for this `run_id`.
    - `ABORTED`: The run with id `run_id` was closed and can no longer be stepped.
    - `UNIMPLEMENTED`: The request asked to step via `max_step` or `max_time`, these are currently unsupported.
    - `INVALID_ARGUMENT`: The request did not specify the run_mode.
    """
    CloseRun: _grpc.UnaryUnaryMultiCallable[_engine_pb2.CloseRunRequest, _engine_pb2.CloseRunResponse]
    """CloseRun closes a run

    Invoking CloseRun causes the specified run to transition to a state where it is no longer possible to call Run or ApplyActions for that run. The connection via `libsumo` is also severed.

    Inputs:

    - `run_id` str: A valid `run_id`, obtained in the response of CreateRun

    Preconditions:

    - A run is not currently executing for `run_id`. A warning will be issued, but the run will be left in an undefined state.
    - The run is not already closed

    Postconditions:

    - All existing subscriptions for this run are cancelled
    - run_id remains preserved to query historical run data.
    - The run will no longer be modifiable via other coroutines.

    Outputs:

    - `run_id` str: The run_id of the run that was just closed.

    Failure Modes:

    - `NOT_FOUND`: The `run_id` was not found in the list of created runs.
    - `INVALID_ARGUMENT`: The specified run was already closed.
    """
    ApplyActions: _grpc.UnaryUnaryMultiCallable[_engine_pb2.ApplyActionsRequest, _engine_pb2.ApplyActionsResponse]
    """ApplyActions"""
    StreamTelemetry: _grpc.UnaryStreamMultiCallable[_engine_pb2.StreamRequest, _engine_pb2.TelemetryFrame]
    """StreamTelemetry"""
    StreamSubscriptions: _grpc.UnaryStreamMultiCallable[_engine_pb2.StreamRequest, _engine_pb2.TelemetryFrame]
    """StreamSubscriptions"""
    Subscribe: _grpc.UnaryUnaryMultiCallable[_engine_pb2.SubscribeRequest, _engine_pb2.SubscribeResponse]
    """Subscribe"""
    Unsubscribe: _grpc.UnaryUnaryMultiCallable[_engine_pb2.UnsubscribeRequest, _engine_pb2.UnsubscribeResponse]
    """Unsubscribe"""
    RegisterInterrupt: _grpc.UnaryUnaryMultiCallable[_engine_pb2.RegisterInterruptRequest, _engine_pb2.RegisterInterruptResponse]
    """RegisterInterrupt"""
    StreamInterrupts: _grpc.UnaryStreamMultiCallable[_engine_pb2.StreamInterruptsRequest, _engine_pb2.InterruptEvent]
    AcknowledgeInterrupt: _grpc.UnaryUnaryMultiCallable[_engine_pb2.AcknowledgeInterruptRequest, _engine_pb2.ApplyActionsResponse]
    """AcknowledgeInterrupt"""
    CancelInterrupt: _grpc.UnaryUnaryMultiCallable[_engine_pb2.CancelInterruptRequest, _engine_pb2.CancelInterruptResponse]
    """CancelInterrupt"""
    FetchSubscription: _grpc.UnaryUnaryMultiCallable[_engine_pb2.FetchRequest, _engine_pb2.FetchResponse]
    """FetchSubscription"""

@_typing.type_check_only
class EngineServiceAsyncStub(EngineServiceStub):
    """EngineSerivce manages a SUMO simulation lifecycle and provides runtime control

    Users can create runs, create subscriptions which will collect data from the simulation
    and make it accessible via SubscriptionStream or FetchSubscription

    Users step the simulation via Run and can change any simulation parameter accessible via
    the TraCI API using ApplyActions. They can also set interrupts via RegisterInterrupt, which
    will interrupt Run requests, by issuing an InterruptEvent. Users must then acknowledge the
    interrupt via AcknowledgeInterrupt and can provide ApplyAction parameters to change the simulation
    before any previously request Run continues. They can also provide new conditions for which the interrupt
    should trigger; by default they are cancelled on acknowledgement.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    CreateRun: _aio.UnaryUnaryMultiCallable[_engine_pb2.CreateRunRequest, _engine_pb2.CreateRunResponse]  # type: ignore[assignment]
    """CreateRun initialises the simulation engine in such a way that it can subsequently be stepped.

    Input:

    - `sumocfg_path` str: A path to a SUMO config file
    - `sumo_binary` str: One of "sumo-gui" or "sumo". Running with "sumo-gui" is experiemental due to a `libsumo` limitation.
    - `step_length_ms` int > 0: Optional integer value which sets how many milliseconds each simulation step should step.

    Preconditions:

    - `SUMO_HOME` must be declared with the correct path to a SUMO executable

    Postconditions:

    - A run_id is returned to the user. All preparations have been made, so any other coroutine can now be used.

    Output:

    - `run_id`: A string containing a UUID for the run that was just created.

    Failure Modes:

    - `INVALID_ARGUMENT`: The run could not be started, such as when the `sumocfg_path` is invalid
    """
    Run: _aio.UnaryUnaryMultiCallable[_engine_pb2.RunRequest, _engine_pb2.RunResponse]  # type: ignore[assignment]
    """Run steps the simulation forward

    Invoking run causes the simulation to step forward by `steps`, `time`, or until `max-steps` or `max-time` are reached.
    For now, only `steps` is supported. Run can be interrupted by registering interrupts via RegisterInterrupt.

    Input:

    - `run_id` str: A valid `run_id`, obtained in the response of CreateRun
    - `run_mode`: ONE OF `steps`, `time`, `max_steps`, or `max_time`. Not `max_steps` and `max_time` are currently unsupported.

    Preconditions:

    - The run was created (implicit because there is no other way to obtain `run_id`) 
    - Only one run can be executing at a time (no concurrent runs).

    Postconditions:

    - The run is stepped as forward as requested. If multiple `run_modes` were specified, the last written field from gRPC's perspective will be used.
    - If interrupt trigger conditions were met, their actions were applied before the next step occurred.

    Output:

    - `run_id`: The run that was just stepped
    - `new_step`: The step number that was last applied; the next step will be `new_step` + 1.
    - `new_time`: The timestamp (in seconds) of the simulation after this Run finished.

    Failure Modes:

    - `NOT_FOUND`: The `run_id` was not found in the list of created runs.
    - `ALREADY_EXISTS`: A run is currently executing for this `run_id`.
    - `ABORTED`: The run with id `run_id` was closed and can no longer be stepped.
    - `UNIMPLEMENTED`: The request asked to step via `max_step` or `max_time`, these are currently unsupported.
    - `INVALID_ARGUMENT`: The request did not specify the run_mode.
    """
    CloseRun: _aio.UnaryUnaryMultiCallable[_engine_pb2.CloseRunRequest, _engine_pb2.CloseRunResponse]  # type: ignore[assignment]
    """CloseRun closes a run

    Invoking CloseRun causes the specified run to transition to a state where it is no longer possible to call Run or ApplyActions for that run. The connection via `libsumo` is also severed.

    Inputs:

    - `run_id` str: A valid `run_id`, obtained in the response of CreateRun

    Preconditions:

    - A run is not currently executing for `run_id`. A warning will be issued, but the run will be left in an undefined state.
    - The run is not already closed

    Postconditions:

    - All existing subscriptions for this run are cancelled
    - run_id remains preserved to query historical run data.
    - The run will no longer be modifiable via other coroutines.

    Outputs:

    - `run_id` str: The run_id of the run that was just closed.

    Failure Modes:

    - `NOT_FOUND`: The `run_id` was not found in the list of created runs.
    - `INVALID_ARGUMENT`: The specified run was already closed.
    """
    ApplyActions: _aio.UnaryUnaryMultiCallable[_engine_pb2.ApplyActionsRequest, _engine_pb2.ApplyActionsResponse]  # type: ignore[assignment]
    """ApplyActions"""
    StreamTelemetry: _aio.UnaryStreamMultiCallable[_engine_pb2.StreamRequest, _engine_pb2.TelemetryFrame]  # type: ignore[assignment]
    """StreamTelemetry"""
    StreamSubscriptions: _aio.UnaryStreamMultiCallable[_engine_pb2.StreamRequest, _engine_pb2.TelemetryFrame]  # type: ignore[assignment]
    """StreamSubscriptions"""
    Subscribe: _aio.UnaryUnaryMultiCallable[_engine_pb2.SubscribeRequest, _engine_pb2.SubscribeResponse]  # type: ignore[assignment]
    """Subscribe"""
    Unsubscribe: _aio.UnaryUnaryMultiCallable[_engine_pb2.UnsubscribeRequest, _engine_pb2.UnsubscribeResponse]  # type: ignore[assignment]
    """Unsubscribe"""
    RegisterInterrupt: _aio.UnaryUnaryMultiCallable[_engine_pb2.RegisterInterruptRequest, _engine_pb2.RegisterInterruptResponse]  # type: ignore[assignment]
    """RegisterInterrupt"""
    StreamInterrupts: _aio.UnaryStreamMultiCallable[_engine_pb2.StreamInterruptsRequest, _engine_pb2.InterruptEvent]  # type: ignore[assignment]
    AcknowledgeInterrupt: _aio.UnaryUnaryMultiCallable[_engine_pb2.AcknowledgeInterruptRequest, _engine_pb2.ApplyActionsResponse]  # type: ignore[assignment]
    """AcknowledgeInterrupt"""
    CancelInterrupt: _aio.UnaryUnaryMultiCallable[_engine_pb2.CancelInterruptRequest, _engine_pb2.CancelInterruptResponse]  # type: ignore[assignment]
    """CancelInterrupt"""
    FetchSubscription: _aio.UnaryUnaryMultiCallable[_engine_pb2.FetchRequest, _engine_pb2.FetchResponse]  # type: ignore[assignment]
    """FetchSubscription"""

class EngineServiceServicer(metaclass=_abc_1.ABCMeta):
    """EngineSerivce manages a SUMO simulation lifecycle and provides runtime control

    Users can create runs, create subscriptions which will collect data from the simulation
    and make it accessible via SubscriptionStream or FetchSubscription

    Users step the simulation via Run and can change any simulation parameter accessible via
    the TraCI API using ApplyActions. They can also set interrupts via RegisterInterrupt, which
    will interrupt Run requests, by issuing an InterruptEvent. Users must then acknowledge the
    interrupt via AcknowledgeInterrupt and can provide ApplyAction parameters to change the simulation
    before any previously request Run continues. They can also provide new conditions for which the interrupt
    should trigger; by default they are cancelled on acknowledgement.
    """

    @_abc_1.abstractmethod
    def CreateRun(
        self,
        request: _engine_pb2.CreateRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.CreateRunResponse, _abc.Awaitable[_engine_pb2.CreateRunResponse]]:
        """CreateRun initialises the simulation engine in such a way that it can subsequently be stepped.

        Input:

        - `sumocfg_path` str: A path to a SUMO config file
        - `sumo_binary` str: One of "sumo-gui" or "sumo". Running with "sumo-gui" is experiemental due to a `libsumo` limitation.
        - `step_length_ms` int > 0: Optional integer value which sets how many milliseconds each simulation step should step.

        Preconditions:

        - `SUMO_HOME` must be declared with the correct path to a SUMO executable

        Postconditions:

        - A run_id is returned to the user. All preparations have been made, so any other coroutine can now be used.

        Output:

        - `run_id`: A string containing a UUID for the run that was just created.

        Failure Modes:

        - `INVALID_ARGUMENT`: The run could not be started, such as when the `sumocfg_path` is invalid
        """

    @_abc_1.abstractmethod
    def Run(
        self,
        request: _engine_pb2.RunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.RunResponse, _abc.Awaitable[_engine_pb2.RunResponse]]:
        """Run steps the simulation forward

        Invoking run causes the simulation to step forward by `steps`, `time`, or until `max-steps` or `max-time` are reached.
        For now, only `steps` is supported. Run can be interrupted by registering interrupts via RegisterInterrupt.

        Input:

        - `run_id` str: A valid `run_id`, obtained in the response of CreateRun
        - `run_mode`: ONE OF `steps`, `time`, `max_steps`, or `max_time`. Not `max_steps` and `max_time` are currently unsupported.

        Preconditions:

        - The run was created (implicit because there is no other way to obtain `run_id`) 
        - Only one run can be executing at a time (no concurrent runs).

        Postconditions:

        - The run is stepped as forward as requested. If multiple `run_modes` were specified, the last written field from gRPC's perspective will be used.
        - If interrupt trigger conditions were met, their actions were applied before the next step occurred.

        Output:

        - `run_id`: The run that was just stepped
        - `new_step`: The step number that was last applied; the next step will be `new_step` + 1.
        - `new_time`: The timestamp (in seconds) of the simulation after this Run finished.

        Failure Modes:

        - `NOT_FOUND`: The `run_id` was not found in the list of created runs.
        - `ALREADY_EXISTS`: A run is currently executing for this `run_id`.
        - `ABORTED`: The run with id `run_id` was closed and can no longer be stepped.
        - `UNIMPLEMENTED`: The request asked to step via `max_step` or `max_time`, these are currently unsupported.
        - `INVALID_ARGUMENT`: The request did not specify the run_mode.
        """

    @_abc_1.abstractmethod
    def CloseRun(
        self,
        request: _engine_pb2.CloseRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.CloseRunResponse, _abc.Awaitable[_engine_pb2.CloseRunResponse]]:
        """CloseRun closes a run

        Invoking CloseRun causes the specified run to transition to a state where it is no longer possible to call Run or ApplyActions for that run. The connection via `libsumo` is also severed.

        Inputs:

        - `run_id` str: A valid `run_id`, obtained in the response of CreateRun

        Preconditions:

        - A run is not currently executing for `run_id`. A warning will be issued, but the run will be left in an undefined state.
        - The run is not already closed

        Postconditions:

        - All existing subscriptions for this run are cancelled
        - run_id remains preserved to query historical run data.
        - The run will no longer be modifiable via other coroutines.

        Outputs:

        - `run_id` str: The run_id of the run that was just closed.

        Failure Modes:

        - `NOT_FOUND`: The `run_id` was not found in the list of created runs.
        - `INVALID_ARGUMENT`: The specified run was already closed.
        """

    @_abc_1.abstractmethod
    def ApplyActions(
        self,
        request: _engine_pb2.ApplyActionsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.ApplyActionsResponse, _abc.Awaitable[_engine_pb2.ApplyActionsResponse]]:
        """ApplyActions"""

    @_abc_1.abstractmethod
    def StreamTelemetry(
        self,
        request: _engine_pb2.StreamRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_engine_pb2.TelemetryFrame], _abc.AsyncIterator[_engine_pb2.TelemetryFrame]]:
        """StreamTelemetry"""

    @_abc_1.abstractmethod
    def StreamSubscriptions(
        self,
        request: _engine_pb2.StreamRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_engine_pb2.TelemetryFrame], _abc.AsyncIterator[_engine_pb2.TelemetryFrame]]:
        """StreamSubscriptions"""

    @_abc_1.abstractmethod
    def Subscribe(
        self,
        request: _engine_pb2.SubscribeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.SubscribeResponse, _abc.Awaitable[_engine_pb2.SubscribeResponse]]:
        """Subscribe"""

    @_abc_1.abstractmethod
    def Unsubscribe(
        self,
        request: _engine_pb2.UnsubscribeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.UnsubscribeResponse, _abc.Awaitable[_engine_pb2.UnsubscribeResponse]]:
        """Unsubscribe"""

    @_abc_1.abstractmethod
    def RegisterInterrupt(
        self,
        request: _engine_pb2.RegisterInterruptRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.RegisterInterruptResponse, _abc.Awaitable[_engine_pb2.RegisterInterruptResponse]]:
        """RegisterInterrupt"""

    @_abc_1.abstractmethod
    def StreamInterrupts(
        self,
        request: _engine_pb2.StreamInterruptsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_engine_pb2.InterruptEvent], _abc.AsyncIterator[_engine_pb2.InterruptEvent]]: ...

    @_abc_1.abstractmethod
    def AcknowledgeInterrupt(
        self,
        request: _engine_pb2.AcknowledgeInterruptRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.ApplyActionsResponse, _abc.Awaitable[_engine_pb2.ApplyActionsResponse]]:
        """AcknowledgeInterrupt"""

    @_abc_1.abstractmethod
    def CancelInterrupt(
        self,
        request: _engine_pb2.CancelInterruptRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.CancelInterruptResponse, _abc.Awaitable[_engine_pb2.CancelInterruptResponse]]:
        """CancelInterrupt"""

    @_abc_1.abstractmethod
    def FetchSubscription(
        self,
        request: _engine_pb2.FetchRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.FetchResponse, _abc.Awaitable[_engine_pb2.FetchResponse]]:
        """FetchSubscription"""

def add_EngineServiceServicer_to_server(servicer: EngineServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
