syntax = "proto3";

import "google/protobuf/struct.proto";

package sumo.engine.v1;

message KeyValue {
    string key = 1;
    reserved 2;
    reserved 3;
    google.protobuf.Value value = 4;
}

message TelemetryFrame {
  string run_id = 1;
  int64 step = 2;
  double sim_time_s = 3;
  repeated KeyValue metrics = 4;
}


message TlsSetPhase {
  string tls_id = 1;
  int32 phase_index = 2;
}

message GenericSetter {
  string domain = 1;
  string setter_name = 2;
  string object_id = 3;
  google.protobuf.Value value = 4;
  repeated Parameter additional_parameters = 5;
}

message Action {
  reserved 1;
  reserved "tls_set_phase";
  oneof payload {
    GenericSetter setter = 2;
  }
}

message ActionBundle {
  string run_id = 1;
  int64 step = 2;
  repeated Action actions = 3;
}

message Artifact {
  string artifact_id = 1;
  string type = 2;
  string uri = 3;
  string sha256 = 4;
}

message CreateRunRequest {
  string sumocfg_path = 1;
  string sumo_binary = 2;
  int32 step_length_ms = 3;
}

message CreateRunResponse {
  string run_id = 1;
  repeated Artifact input_artifacts = 2;
}

message RunRequest {
  string run_id = 1;
  reserved 2; // used to only support max_steps

  oneof max_run {
    int32 max_steps = 3;
    float max_time = 4;
  }
}

message RunResponse {
  string run_id = 1;
  uint64 new_step = 5;
}

message CloseRunRequest {
  string run_id = 1;
}

message CloseRunResponse {
  string run_id = 1;
  // maybe can return some analytics also?
}

message ApplyActionsResponse {
  string run_id = 1;
}

message StreamRequest {
  string run_id = 1;
}

message Parameter {
  string name = 1;
  google.protobuf.Value value = 2;
}

message SubscribeRequest {
  string run_id = 1;
  string domain = 2;
  string getter_name = 3;
  optional string object_id = 4;
  repeated Parameter additional_parameters = 5;
  optional string name = 6;
}

message SubscribeResponse {
  string fingerprint = 1;
}

message UnsubscribeRequest {
  string run_id = 1;
}

message UnsubscribeResponse {
  string run_id = 1;
}

enum Operation {
  EQU = 0;
  NEQ = 1;
  GRT = 2;
  LST = 3;
  GEQ = 4;
  LEQ = 5;
}

message MetricNameAndValue {
  // TODO coalesce with Parameter, which shares name and value
  string name = 1;
  google.protobuf.Value value = 2;
  Operation op = 3;
}

message RegisterInterruptRequest {
  string run_id = 1;
  reserved "trigger_metric_name", "trigger_metric_value";
  reserved 2, 3;
  // string trigger_metric_name = 2;
  // google.protobuf.Value trigger_metric_value = 3;
  MetricNameAndValue trigger_metric = 4;
}

message InterruptEvent {
  string interrupt_id = 1;
  string event_id = 2;
  // maybe following fields optional?
  google.protobuf.Value observed_value = 3;
}

message AcknowledgeInterruptRequest {
  string run_id = 1;
  string interrupt_id = 2;
  string event_id = 3;
  ActionBundle actions = 4;
  MetricNameAndValue new_interrupt_conditions = 5;
}

message CancelInterruptRequest {
  string run_id = 1;
  string interrupt_id = 2;
}

message CancelInterruptResponse {
  string interrupt_id = 1;
}

service EngineService {
  rpc CreateRun(CreateRunRequest) returns (CreateRunResponse);
  rpc Run(RunRequest) returns (RunResponse);
  rpc CloseRun(CloseRunRequest) returns (CloseRunResponse);
  rpc ApplyActions(ActionBundle) returns (ApplyActionsResponse);
  rpc StreamTelemetry(StreamRequest) returns (stream TelemetryFrame);
  rpc StreamSubscriptions(StreamRequest) returns (stream TelemetryFrame);
  rpc Subscribe(SubscribeRequest) returns (SubscribeResponse);
  rpc Unsubscribe(UnsubscribeRequest) returns (UnsubscribeResponse);
  rpc RegisterInterrupt(RegisterInterruptRequest) returns (stream InterruptEvent);
  rpc AcknowledgeInterrupt(AcknowledgeInterruptRequest) returns (ApplyActionsResponse);
  rpc CancelInterrupt(CancelInterruptRequest) returns (CancelInterruptResponse);
}

