"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Operation:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _OperationEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Operation.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    EQU: _Operation.ValueType  # 0
    NEQ: _Operation.ValueType  # 1
    GRT: _Operation.ValueType  # 2
    LST: _Operation.ValueType  # 3
    GEQ: _Operation.ValueType  # 4
    LEQ: _Operation.ValueType  # 5

class Operation(_Operation, metaclass=_OperationEnumTypeWrapper): ...

EQU: Operation.ValueType  # 0
NEQ: Operation.ValueType  # 1
GRT: Operation.ValueType  # 2
LST: Operation.ValueType  # 3
GEQ: Operation.ValueType  # 4
LEQ: Operation.ValueType  # 5
Global___Operation: _TypeAlias = Operation  # noqa: Y015

@_typing.final
class KeyValue(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    @_builtins.property
    def value(self) -> _struct_pb2.Value: ...
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _struct_pb2.Value | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KeyValue: _TypeAlias = KeyValue  # noqa: Y015

@_typing.final
class TelemetryFrame(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    STEP_FIELD_NUMBER: _builtins.int
    SIM_TIME_S_FIELD_NUMBER: _builtins.int
    METRICS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    step: _builtins.int
    sim_time_s: _builtins.float
    @_builtins.property
    def metrics(self) -> _containers.RepeatedCompositeFieldContainer[Global___KeyValue]: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        step: _builtins.int = ...,
        sim_time_s: _builtins.float = ...,
        metrics: _abc.Iterable[Global___KeyValue] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["metrics", b"metrics", "run_id", b"run_id", "sim_time_s", b"sim_time_s", "step", b"step"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TelemetryFrame: _TypeAlias = TelemetryFrame  # noqa: Y015

@_typing.final
class TlsSetPhase(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TLS_ID_FIELD_NUMBER: _builtins.int
    PHASE_INDEX_FIELD_NUMBER: _builtins.int
    tls_id: _builtins.str
    phase_index: _builtins.int
    def __init__(
        self,
        *,
        tls_id: _builtins.str = ...,
        phase_index: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["phase_index", b"phase_index", "tls_id", b"tls_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TlsSetPhase: _TypeAlias = TlsSetPhase  # noqa: Y015

@_typing.final
class GenericSetter(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DOMAIN_FIELD_NUMBER: _builtins.int
    SETTER_NAME_FIELD_NUMBER: _builtins.int
    PARAMETERS_FIELD_NUMBER: _builtins.int
    domain: _builtins.str
    setter_name: _builtins.str
    @_builtins.property
    def parameters(self) -> _containers.RepeatedCompositeFieldContainer[Global___Parameter]: ...
    def __init__(
        self,
        *,
        domain: _builtins.str = ...,
        setter_name: _builtins.str = ...,
        parameters: _abc.Iterable[Global___Parameter] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["domain", b"domain", "parameters", b"parameters", "setter_name", b"setter_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GenericSetter: _TypeAlias = GenericSetter  # noqa: Y015

@_typing.final
class Action(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SETTER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def setter(self) -> Global___GenericSetter: ...
    def __init__(
        self,
        *,
        setter: Global___GenericSetter | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "setter", b"setter"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "setter", b"setter"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["setter"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___Action: _TypeAlias = Action  # noqa: Y015

@_typing.final
class ActionBundle(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    STEP_FIELD_NUMBER: _builtins.int
    ACTIONS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    step: _builtins.int
    @_builtins.property
    def actions(self) -> _containers.RepeatedCompositeFieldContainer[Global___Action]: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        step: _builtins.int | None = ...,
        actions: _abc.Iterable[Global___Action] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_step", b"_step", "step", b"step"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_step", b"_step", "actions", b"actions", "run_id", b"run_id", "step", b"step"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__step: _TypeAlias = _typing.Literal["step"]  # noqa: Y015
    _WhichOneofArgType__step: _TypeAlias = _typing.Literal["_step", b"_step"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__step) -> _WhichOneofReturnType__step | None: ...

Global___ActionBundle: _TypeAlias = ActionBundle  # noqa: Y015

@_typing.final
class Artifact(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ARTIFACT_ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    URI_FIELD_NUMBER: _builtins.int
    SHA256_FIELD_NUMBER: _builtins.int
    artifact_id: _builtins.str
    type: _builtins.str
    uri: _builtins.str
    sha256: _builtins.str
    def __init__(
        self,
        *,
        artifact_id: _builtins.str = ...,
        type: _builtins.str = ...,
        uri: _builtins.str = ...,
        sha256: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["artifact_id", b"artifact_id", "sha256", b"sha256", "type", b"type", "uri", b"uri"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Artifact: _TypeAlias = Artifact  # noqa: Y015

@_typing.final
class CreateRunRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUMOCFG_PATH_FIELD_NUMBER: _builtins.int
    SUMO_BINARY_FIELD_NUMBER: _builtins.int
    STEP_LENGTH_MS_FIELD_NUMBER: _builtins.int
    sumocfg_path: _builtins.str
    sumo_binary: _builtins.str
    step_length_ms: _builtins.int
    def __init__(
        self,
        *,
        sumocfg_path: _builtins.str = ...,
        sumo_binary: _builtins.str = ...,
        step_length_ms: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["step_length_ms", b"step_length_ms", "sumo_binary", b"sumo_binary", "sumocfg_path", b"sumocfg_path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateRunRequest: _TypeAlias = CreateRunRequest  # noqa: Y015

@_typing.final
class CreateRunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    INPUT_ARTIFACTS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    @_builtins.property
    def input_artifacts(self) -> _containers.RepeatedCompositeFieldContainer[Global___Artifact]: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        input_artifacts: _abc.Iterable[Global___Artifact] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["input_artifacts", b"input_artifacts", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateRunResponse: _TypeAlias = CreateRunResponse  # noqa: Y015

@_typing.final
class RunRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    MAX_STEPS_FIELD_NUMBER: _builtins.int
    MAX_TIME_FIELD_NUMBER: _builtins.int
    STEPS_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    max_steps: _builtins.int
    max_time: _builtins.float
    steps: _builtins.int
    time: _builtins.float
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        max_steps: _builtins.int = ...,
        max_time: _builtins.float = ...,
        steps: _builtins.int = ...,
        time: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["max_steps", b"max_steps", "max_time", b"max_time", "run_mode", b"run_mode", "steps", b"steps", "time", b"time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_steps", b"max_steps", "max_time", b"max_time", "run_id", b"run_id", "run_mode", b"run_mode", "steps", b"steps", "time", b"time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_run_mode: _TypeAlias = _typing.Literal["max_steps", "max_time", "steps", "time"]  # noqa: Y015
    _WhichOneofArgType_run_mode: _TypeAlias = _typing.Literal["run_mode", b"run_mode"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_run_mode) -> _WhichOneofReturnType_run_mode | None: ...

Global___RunRequest: _TypeAlias = RunRequest  # noqa: Y015

@_typing.final
class RunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    NEW_STEP_FIELD_NUMBER: _builtins.int
    NEW_TIME_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    new_step: _builtins.int
    new_time: _builtins.float
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        new_step: _builtins.int = ...,
        new_time: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["new_step", b"new_step", "new_time", b"new_time", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RunResponse: _TypeAlias = RunResponse  # noqa: Y015

@_typing.final
class CloseRunRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CloseRunRequest: _TypeAlias = CloseRunRequest  # noqa: Y015

@_typing.final
class CloseRunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """maybe can return some analytics also?"""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CloseRunResponse: _TypeAlias = CloseRunResponse  # noqa: Y015

@_typing.final
class ApplyActionsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApplyActionsResponse: _TypeAlias = ApplyActionsResponse  # noqa: Y015

@_typing.final
class StreamRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamRequest: _TypeAlias = StreamRequest  # noqa: Y015

@_typing.final
class Parameter(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    @_builtins.property
    def value(self) -> _struct_pb2.Value: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        value: _struct_pb2.Value | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Parameter: _TypeAlias = Parameter  # noqa: Y015

@_typing.final
class SubscribeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    DOMAIN_FIELD_NUMBER: _builtins.int
    GETTER_NAME_FIELD_NUMBER: _builtins.int
    PARAMETERS_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    domain: _builtins.str
    getter_name: _builtins.str
    name: _builtins.str
    @_builtins.property
    def parameters(self) -> _containers.RepeatedCompositeFieldContainer[Global___Parameter]: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        domain: _builtins.str = ...,
        getter_name: _builtins.str = ...,
        parameters: _abc.Iterable[Global___Parameter] | None = ...,
        name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "name", b"name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "domain", b"domain", "getter_name", b"getter_name", "name", b"name", "parameters", b"parameters", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...

Global___SubscribeRequest: _TypeAlias = SubscribeRequest  # noqa: Y015

@_typing.final
class SubscribeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FINGERPRINT_FIELD_NUMBER: _builtins.int
    fingerprint: _builtins.str
    def __init__(
        self,
        *,
        fingerprint: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fingerprint", b"fingerprint"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeResponse: _TypeAlias = SubscribeResponse  # noqa: Y015

@_typing.final
class UnsubscribeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnsubscribeRequest: _TypeAlias = UnsubscribeRequest  # noqa: Y015

@_typing.final
class UnsubscribeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnsubscribeResponse: _TypeAlias = UnsubscribeResponse  # noqa: Y015

@_typing.final
class MetricNameAndValue(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    OP_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """TODO coalesce with Parameter, which shares name and value"""
    op: Global___Operation.ValueType
    @_builtins.property
    def value(self) -> _struct_pb2.Value: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        value: _struct_pb2.Value | None = ...,
        op: Global___Operation.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "op", b"op", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MetricNameAndValue: _TypeAlias = MetricNameAndValue  # noqa: Y015

@_typing.final
class RegisterInterruptRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    TRIGGER_METRIC_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    @_builtins.property
    def trigger_metric(self) -> Global___MetricNameAndValue:
        """string trigger_metric_name = 2;
        google.protobuf.Value trigger_metric_value = 3;
        """

    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        trigger_metric: Global___MetricNameAndValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["trigger_metric", b"trigger_metric"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id", "trigger_metric", b"trigger_metric"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RegisterInterruptRequest: _TypeAlias = RegisterInterruptRequest  # noqa: Y015

@_typing.final
class InterruptEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INTERRUPT_ID_FIELD_NUMBER: _builtins.int
    EVENT_ID_FIELD_NUMBER: _builtins.int
    OBSERVED_VALUE_FIELD_NUMBER: _builtins.int
    interrupt_id: _builtins.str
    event_id: _builtins.str
    @_builtins.property
    def observed_value(self) -> _struct_pb2.Value:
        """maybe following fields optional?"""

    def __init__(
        self,
        *,
        interrupt_id: _builtins.str = ...,
        event_id: _builtins.str = ...,
        observed_value: _struct_pb2.Value | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["observed_value", b"observed_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event_id", b"event_id", "interrupt_id", b"interrupt_id", "observed_value", b"observed_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___InterruptEvent: _TypeAlias = InterruptEvent  # noqa: Y015

@_typing.final
class AcknowledgeInterruptRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    INTERRUPT_ID_FIELD_NUMBER: _builtins.int
    EVENT_ID_FIELD_NUMBER: _builtins.int
    ACTIONS_FIELD_NUMBER: _builtins.int
    NEW_INTERRUPT_CONDITIONS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    interrupt_id: _builtins.str
    event_id: _builtins.str
    @_builtins.property
    def actions(self) -> Global___ActionBundle: ...
    @_builtins.property
    def new_interrupt_conditions(self) -> Global___MetricNameAndValue: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        interrupt_id: _builtins.str = ...,
        event_id: _builtins.str = ...,
        actions: Global___ActionBundle | None = ...,
        new_interrupt_conditions: Global___MetricNameAndValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["actions", b"actions", "new_interrupt_conditions", b"new_interrupt_conditions"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actions", b"actions", "event_id", b"event_id", "interrupt_id", b"interrupt_id", "new_interrupt_conditions", b"new_interrupt_conditions", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AcknowledgeInterruptRequest: _TypeAlias = AcknowledgeInterruptRequest  # noqa: Y015

@_typing.final
class CancelInterruptRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    INTERRUPT_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    interrupt_id: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        interrupt_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["interrupt_id", b"interrupt_id", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CancelInterruptRequest: _TypeAlias = CancelInterruptRequest  # noqa: Y015

@_typing.final
class CancelInterruptResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INTERRUPT_ID_FIELD_NUMBER: _builtins.int
    interrupt_id: _builtins.str
    def __init__(
        self,
        *,
        interrupt_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["interrupt_id", b"interrupt_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CancelInterruptResponse: _TypeAlias = CancelInterruptResponse  # noqa: Y015
